### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by davidliang781205** [esl/sparrow#16]
Typo in readme `{:sparrow, github: "esl/sprrow", tag: "cc80bbc"},`
to `{:sparrow, github: "esl/sparrow", tag: "cc80bbc"},`

**Comment by aleklisi** [comment]
@davidliang781205  thanks for reporting Issue, will be fixed in https://github.com/esl/sparrow/pull/17

**Comment by aleklisi** [comment]
PR merged case closed thanks again :)
