### ISSUE TITLE
Project state and hex.pm

### ISSUE THREAD

**Issue by cybrox** [esl/sparrow#49]
Hello everyone,

I have not found any other feedback channel, so I'm opening an issue for this question. I have been using [codedge-llc/pigeon](https://github.com/codedge-llc/pigeon) for handling push notifications in the past but am looking for alternatives due to some missing features. (APNS headers)

Sparrow looks like a complete, well-tested implementation of all essential mobile push services. And as far as I can see, has been used in production already, so it would be a perfect fit. Yet, looking at the repository it looks a bit experimental. Is there a reason why this has not been published on hex.pm yet?

Thanks!

**Comment by pawlooss1** [comment]
Thanks for the issue. It's been a while and we're refreshing the state of both sparrow and MongoosePush. We'll definitely consider publishing this library on hex.pm. For now everyone interested in it is welcome to use it as a dependency straight from the source.
